# Refs to https://github.com/hugo-fixit/docs/blob/main/config/_default/taxonomies.toml

# -------------------------------------------------------------------------------------
# Taxonomies Configuration | 分类法配置
# See: https://gohugo.io/content-management/taxonomies/#configure-taxonomies
# -------------------------------------------------------------------------------------

category = "categories"
tag = "tags"
collection = "collections"
